from tkinter import *
import ttkthemes

def select(event):
    b=event.widget
    value=b['text']
    if value=='Space':
        textarea.insert(INSERT,' ')
    elif value=='Enter':
        textarea.insert(INSERT, '\n')
    elif value=='Tab':
        textarea.insert(INSERT, '\t')
    elif value=='Del':
        textarea.delete(1.0,END)

    elif value=='Backs':
        i=textarea.get(1.0,END)
        newtext=i[:-2]
        textarea.delete(1.0,END)
        textarea.insert(INSERT,newtext)
    elif value=='Caps':
        buttoncaps.grid_remove()
        buttonCAPS.grid()

        buttona.config(text='A')
        buttonb.config(text='B')
        buttonc.config(text='C')
        buttond.config(text='D')
        buttone.config(text='E')
        buttonf.config(text='F')
        buttong.config(text='G')
        buttonh.config(text='H')
        buttoni.config(text='I')
        buttonj.config(text='J')
        buttonk.config(text='K')
        buttonl.config(text='L')
        buttonm.config(text='M')
        buttonn.config(text='N')
        buttono.config(text='O')
        buttonp.config(text='P')
        buttonq.config(text='Q')
        buttonr.config(text='R')
        buttons.config(text='S')
        buttont.config(text='T')
        buttonu.config(text='U')
        buttonv.config(text='V')
        buttonw.config(text='W')
        buttonx.config(text='X')
        buttony.config(text='Y')
        buttonz.config(text='Z')
    elif value=='CAPS':
        buttonCAPS.grid_remove()
        buttoncaps.grid()

        buttona.config(text='a')
        buttonb.config(text='b')
        buttonc.config(text='c')
        buttond.config(text='d')
        buttone.config(text='e')
        buttonf.config(text='f')
        buttong.config(text='g')
        buttonh.config(text='h')
        buttoni.config(text='i')
        buttonj.config(text='j')
        buttonk.config(text='k')
        buttonl.config(text='l')
        buttonm.config(text='m')
        buttonn.config(text='n')
        buttono.config(text='o')
        buttonp.config(text='p')
        buttonq.config(text='q')
        buttonr.config(text='r')
        buttons.config(text='s')
        buttont.config(text='t')
        buttonu.config(text='u')
        buttonv.config(text='v')
        buttonw.config(text='w')
        buttonx.config(text='x')
        buttony.config(text='y')
        buttonz.config(text='z')

    else:
        textarea.insert(INSERT,value)

def shift():
    aapostrophyButton.grid_remove()
    button1.grid_remove()
    button2.grid_remove()
    button3.grid_remove()
    button4.grid_remove()
    button5.grid_remove()
    button6.grid_remove()
    button7.grid_remove()
    button8.grid_remove()
    button9.grid_remove()
    button0.grid_remove()
    buttonminus.grid_remove()
    buttonequalsto.grid_remove()
    buttonopenbracket.grid_remove()
    buttonclosebracket.grid_remove()
    buttonsemicolon.grid_remove()
    buttoncomma.grid_remove()
    buttonfullstop.grid_remove()
    buttonsinglequote.grid_remove()
    buttonforwardslash.grid_remove()
    buttonbackslash.grid_remove()


    tildButton.grid()
    buttonexclamation.grid()
    buttonattherate.grid()
    buttonhashtag.grid()
    buttondollar.grid()
    buttonpercentile.grid()
    buttonpower.grid()
    buttonampersand.grid()
    buttonasterisk.grid()
    buttonopenparenthesis.grid()
    buttoncloseparenthesis.grid()
    buttonunderscore.grid()
    buttonplus.grid()
    buttonopenbrace.grid()
    buttonclosebrace.grid()
    buttoncolon.grid()
    buttonquote.grid()
    buttongreaterthan.grid()
    buttonlessthan.grid()
    buttonquestionmark.grid()
    buttonpipe.grid()


def shift1():
    tildButton.grid_remove()
    buttonexclamation.grid_remove()
    buttonattherate.grid_remove()
    buttonhashtag.grid_remove()
    buttondollar.grid_remove()
    buttonpercentile.grid_remove()
    buttonpower.grid_remove()
    buttonampersand.grid_remove()
    buttonasterisk.grid_remove()
    buttonopenparenthesis.grid_remove()
    buttoncloseparenthesis.grid_remove()
    buttonunderscore.grid_remove()
    buttonplus.grid_remove()
    buttonopenbrace.grid_remove()
    buttonclosebrace.grid_remove()
    buttoncolon.grid_remove()
    buttonquote.grid_remove()
    buttongreaterthan.grid_remove()
    buttonlessthan.grid_remove()
    buttonquestionmark.grid_remove()
    buttonpipe.grid_remove()


    aapostrophyButton.grid()
    button1.grid()
    button2.grid()
    button3.grid()
    button4.grid()
    button5.grid()
    button6.grid()
    button7.grid()
    button8.grid()
    button9.grid()
    button0.grid()
    buttonminus.grid()
    buttonequalsto.grid()
    buttonopenbracket.grid()
    buttonclosebracket.grid()
    buttonsemicolon.grid()
    buttoncomma.grid()
    buttonfullstop.grid()
    buttonsinglequote.grid()
    buttonforwardslash.grid()
    buttonbackslash.grid()



from tkinter import ttk


root=ttkthemes.ThemedTk()

root.get_themes()

root.set_theme('radiance')



root.title('On-Screen Keyboard')
root.config(bg='gray30')
root.resizable(False,False)

titleLabel=Label(root,text="On Screen Keyboard", font=('arial',20,'bold'),bg='gray30',foreground='white')
titleLabel.grid(row=0,column=0,columnspan=40)
textarea=Text(root,width=100,height=10,font=('arial',15,'bold'))
textarea.grid(row=1,column=0,columnspan=40)
textarea.focus_set()

keysframe=Frame(root)
keysframe.grid(row=2,column=0)

aapostrophyButton=ttk.Button(keysframe,text='`',width=5)
aapostrophyButton.grid(row=0,column=0)
tildButton=ttk.Button(keysframe,text='~',width=5)
tildButton.grid(row=0,column=0)
tildButton.grid_remove()

button1=ttk.Button(keysframe,text='1',width=5)
button1.grid(row=0,column=1)
buttonexclamation=ttk.Button(keysframe,text='!',width=5)
buttonexclamation.grid(row=0,column=1)
buttonexclamation.grid_remove()
button2=ttk.Button(keysframe,text='2',width=5)
button2.grid(row=0,column=2)
buttonattherate=ttk.Button(keysframe,text='@',width=5)
buttonattherate.grid(row=0,column=2)
buttonattherate.grid_remove()
button3=ttk.Button(keysframe,text='3',width=5)
button3.grid(row=0,column=3)
buttonhashtag=ttk.Button(keysframe,text='#',width=5)
buttonhashtag.grid(row=0,column=3)
buttonhashtag.grid_remove()
button4=ttk.Button(keysframe,text='4',width=5)
button4.grid(row=0,column=4)
buttondollar=ttk.Button(keysframe,text='$',width=5)
buttondollar.grid(row=0,column=4)
buttondollar.grid_remove()
button5=ttk.Button(keysframe,text='5',width=5)
button5.grid(row=0,column=5)
buttonpercentile=ttk.Button(keysframe,text='%',width=5)
buttonpercentile.grid(row=0,column=5)
buttonpercentile.grid_remove()
button6=ttk.Button(keysframe,text='6',width=5)
button6.grid(row=0,column=6)
buttonpower=ttk.Button(keysframe,text='^',width=5)
buttonpower.grid(row=0,column=6)
buttonpower.grid_remove()
button7=ttk.Button(keysframe,text='7',width=5)
button7.grid(row=0,column=7)
buttonampersand=ttk.Button(keysframe,text='&',width=5)
buttonampersand.grid(row=0,column=7)
buttonampersand.grid_remove()
button8=ttk.Button(keysframe,text='8',width=5)
button8.grid(row=0,column=8)
buttonasterisk=ttk.Button(keysframe,text='*',width=5)
buttonasterisk.grid(row=0,column=8)
buttonasterisk.grid_remove()
button9=ttk.Button(keysframe,text='9',width=5)
button9.grid(row=0,column=9)
buttonopenparenthesis=ttk.Button(keysframe,text='(',width=5)
buttonopenparenthesis.grid(row=0,column=9)
buttonopenparenthesis.grid_remove()
button0=ttk.Button(keysframe,text='0',width=5)
button0.grid(row=0,column=10)
buttoncloseparenthesis=ttk.Button(keysframe,text=')',width=5)
buttoncloseparenthesis.grid(row=0,column=10)
buttoncloseparenthesis.grid_remove()
buttonminus=ttk.Button(keysframe,text='-',width=5)
buttonminus.grid(row=0,column=11)
buttonunderscore=ttk.Button(keysframe,text='_',width=5)
buttonunderscore.grid(row=0,column=11)
buttonunderscore.grid_remove()
buttonplus=ttk.Button(keysframe,text='+',width=5)
buttonplus.grid(row=0,column=12)
buttonplus.grid_remove()
buttonequalsto=ttk.Button(keysframe,text='=',width=5)
buttonequalsto.grid(row=0,column=12)
buttonBacks=ttk.Button(keysframe,text='Backs',width=5)
buttonBacks.grid(row=0,column=13)
buttonDel=ttk.Button(keysframe,text='Del',width=5)
buttonDel.grid(row=0,column=14)
buttonInsert=ttk.Button(keysframe,text='Insert',width=5)
buttonInsert.grid(row=0,column=15)


buttonTab=ttk.Button(keysframe,text='Tab',width=5)
buttonTab.grid(row=1,column=0)
buttonq=ttk.Button(keysframe,text='q',width=5)
buttonq.grid(row=1,column=1)
buttonw=ttk.Button(keysframe,text='w',width=5)
buttonw.grid(row=1,column=2)
buttone=ttk.Button(keysframe,text='e',width=5)
buttone.grid(row=1,column=3)
buttonr=ttk.Button(keysframe,text='r',width=5)
buttonr.grid(row=1,column=4)
buttont=ttk.Button(keysframe,text='t',width=5)
buttont.grid(row=1,column=5)
buttony=ttk.Button(keysframe,text='y',width=5)
buttony.grid(row=1,column=6)
buttonu=ttk.Button(keysframe,text='U',width=5)
buttonu.grid(row=1,column=7)
buttoni=ttk.Button(keysframe,text='i',width=5)
buttoni.grid(row=1,column=8)
buttono=ttk.Button(keysframe,text='o',width=5)
buttono.grid(row=1,column=9)
buttonp=ttk.Button(keysframe,text='p',width=5)
buttonp.grid(row=1,column=10)
buttonopenbracket=ttk.Button(keysframe,text='[',width=5)
buttonopenbracket.grid(row=1,column=11)
buttonopenbrace=ttk.Button(keysframe,text='{',width=5)
buttonopenbrace.grid(row=1,column=11)
buttonopenbrace.grid_remove()
buttonclosebracket=ttk.Button(keysframe,text=']',width=5)
buttonclosebracket.grid(row=1,column=12)
buttonclosebrace=ttk.Button(keysframe,text='}',width=5)
buttonclosebrace.grid(row=1,column=12)
buttonclosebrace.grid_remove()
buttonpipe=ttk.Button(keysframe,text='|',width=5)
buttonpipe.grid(row=1,column=13)
buttonpipe.grid_remove()
buttonbackslash=ttk.Button(keysframe,text="\\",width=5)
buttonbackslash.grid(row=1,column=13)
buttonseven=ttk.Button(keysframe,text='7',width=5)
buttonseven.grid(row=1,column=14)
buttoneight=ttk.Button(keysframe,text='8',width=5)
buttoneight.grid(row=1,column=14)
buttonnine=ttk.Button(keysframe,text='9',width=5)
buttonnine.grid(row=1,column=15)

buttoncaps=ttk.Button(keysframe,text='Caps',width=5)
buttoncaps.grid(row=2,column=0)
buttonCAPS=ttk.Button(keysframe,text='CAPS',width=5)
buttonCAPS.grid(row=2,column=0)
buttonCAPS.grid_remove()
buttona=ttk.Button(keysframe,text='a',width=5)
buttona.grid(row=2,column=1)
buttons=ttk.Button(keysframe,text='s',width=5)
buttons.grid(row=2,column=2)
buttond=ttk.Button(keysframe,text='d',width=5)
buttond.grid(row=2,column=3)
buttonf=ttk.Button(keysframe,text='f',width=5)
buttonf.grid(row=2,column=4)
buttong=ttk.Button(keysframe,text='g',width=5)
buttong.grid(row=2,column=5)
buttonh=ttk.Button(keysframe,text='h',width=5)
buttonh.grid(row=2,column=6)
buttonj=ttk.Button(keysframe,text='j',width=5)
buttonj.grid(row=2,column=7)
buttonk=ttk.Button(keysframe,text='k',width=5)
buttonk.grid(row=2,column=8)
buttonl=ttk.Button(keysframe,text='l',width=5)
buttonl.grid(row=2,column=9)
buttoncolon=ttk.Button(keysframe,text=':',width=5)
buttoncolon.grid(row=2,column=10)
buttoncolon.grid_remove()
buttonsemicolon=ttk.Button(keysframe,text=';',width=5)
buttonsemicolon.grid(row=2,column=10)
buttonquote=ttk.Button(keysframe,text='"',width=5)
buttonquote.grid(row=2,column=11)
buttonquote.grid_remove()
buttonsinglequote=ttk.Button(keysframe,text="'",width=5)
buttonsinglequote.grid(row=2,column=11)
buttonEnter=ttk.Button(keysframe,text='Enter',width=5)
buttonEnter.grid(row=2,column=12)
buttonfour=ttk.Button(keysframe,text='4',width=5)
buttonfour.grid(row=2,column=13)
buttonfive=ttk.Button(keysframe,text='5',width=5)
buttonfive.grid(row=2,column=14)
buttonsix=ttk.Button(keysframe,text='6',width=5)
buttonsix.grid(row=2,column=15)

buttonshift=ttk.Button(keysframe,text='Shift',width=5,command=shift)
buttonshift.grid(row=3,column=0)
buttonz=ttk.Button(keysframe,text='z',width=5)
buttonz.grid(row=3,column=1)
buttonx=ttk.Button(keysframe,text='x',width=5)
buttonx.grid(row=3,column=2)
buttonc=ttk.Button(keysframe,text='c',width=5)
buttonc.grid(row=3,column=3)
buttonv=ttk.Button(keysframe,text='v',width=5)
buttonv.grid(row=3,column=4)
buttonb=ttk.Button(keysframe,text='b',width=5)
buttonb.grid(row=3,column=5)
buttonn=ttk.Button(keysframe,text='n',width=5)
buttonn.grid(row=3,column=6)
buttonm=ttk.Button(keysframe,text='m',width=5)
buttonm.grid(row=3,column=7)
buttoncomma=ttk.Button(keysframe,text=',',width=5)
buttoncomma.grid(row=3,column=8)
buttonlessthan=ttk.Button(keysframe,text='<',width=5)
buttonlessthan.grid(row=3,column=8)
buttonlessthan.grid_remove()
buttonfullstop=ttk.Button(keysframe,text='.',width=5)
buttonfullstop.grid(row=3,column=9)
buttongreaterthan=ttk.Button(keysframe,text='>',width=5)
buttongreaterthan.grid(row=3,column=9)
buttongreaterthan.grid_remove()
buttonforwardslash=ttk.Button(keysframe,text='/',width=5)
buttonforwardslash.grid(row=3,column=10)
buttonquestionmark=ttk.Button(keysframe,text='?',width=5)
buttonquestionmark.grid(row=3,column=10)
buttonquestionmark.grid_remove()
buttonshift1=ttk.Button(keysframe,text='Shift',width=5,command=shift1)
buttonshift1.grid(row=3,column=11)
buttonone=ttk.Button(keysframe,text='1',width=5)
buttonone.grid(row=3,column=12)
buttontwo=ttk.Button(keysframe,text='2',width=5)
buttontwo.grid(row=3,column=13)
buttonthree=ttk.Button(keysframe,text='3',width=5)
buttonthree.grid(row=3,column=14)


buttonspace=ttk.Button(keysframe,text='Space',width=30)
buttonspace.grid(row=4,column=0,columnspan=40)


button1.bind('<Button-1>',select)
button2.bind('<Button-1>',select)
button3.bind('<Button-1>',select)
button4.bind('<Button-1>',select)
button5.bind('<Button-1>',select)
button6.bind('<Button-1>',select)
button7.bind('<Button-1>',select)
button8.bind('<Button-1>',select)
button9.bind('<Button-1>',select)
button0.bind('<Button-1>',select)
aapostrophyButton.bind('<Button-1>',select)
tildButton.bind('<Button-1>',select)
buttonminus.bind('<Button-1>',select)
buttonequalsto.bind('<Button-1>',select)
buttonBacks.bind('<Button-1>',select)
buttonDel.bind('<Button-1>',select)
buttonq.bind('<Button-1>',select)
buttonw.bind('<Button-1>',select)
buttone.bind('<Button-1>',select)
buttonr.bind('<Button-1>',select)
buttont.bind('<Button-1>',select)
buttony.bind('<Button-1>',select)
buttonu.bind('<Button-1>',select)
buttoni.bind('<Button-1>',select)
buttono.bind('<Button-1>',select)
buttonp.bind('<Button-1>',select)
buttona.bind('<Button-1>',select)
buttons.bind('<Button-1>',select)
buttond.bind('<Button-1>',select)
buttonf.bind('<Button-1>',select)
buttong.bind('<Button-1>',select)
buttonh.bind('<Button-1>',select)
buttonj.bind('<Button-1>',select)
buttonk.bind('<Button-1>',select)
buttonl.bind('<Button-1>',select)
buttonz.bind('<Button-1>',select)
buttonx.bind('<Button-1>',select)
buttonc.bind('<Button-1>',select)
buttonv.bind('<Button-1>',select)
buttonb.bind('<Button-1>',select)
buttonn.bind('<Button-1>',select)
buttonm.bind('<Button-1>',select)
buttoncolon.bind('<Button-1>',select)
buttoncomma.bind('<Button-1>',select)
buttonforwardslash.bind('<Button-1>',select)
buttoncaps.bind('<Button-1>',select)
buttonCAPS.bind('<Button-1>',select)
buttonone.bind('<Button-1>',select)
buttontwo.bind('<Button-1>',select)
buttonthree.bind('<Button-1>',select)
buttonfour.bind('<Button-1>',select)
buttonfive.bind('<Button-1>',select)
buttonsix.bind('<Button-1>',select)
buttonseven.bind('<Button-1>',select)
buttoneight.bind('<Button-1>',select)
buttonnine.bind('<Button-1>',select)
buttonspace.bind('<Button-1>',select)
buttonEnter.bind('<Button-1>',select)
buttonopenbrace.bind('<Button-1>',select)
buttonclosebrace.bind('<Button-1>',select)
buttonTab.bind('<Button-1>',select)
buttonfullstop.bind('<Button-1>',select)
buttonexclamation.bind('<Button-1>',select)
buttonattherate.bind('<Button-1>',select)
buttonhashtag.bind('<Button-1>',select)
buttondollar.bind('<Button-1>',select)
buttonampersand.bind('<Button-1>',select)
buttonpower.bind('<Button-1>',select)
buttonpercentile.bind('<Button-1>',select)
buttonasterisk.bind('<Button-1>',select)
buttonopenparenthesis.bind('<Button-1>',select)
buttoncloseparenthesis.bind('<Button-1>',select)
buttonunderscore.bind('<Button-1>',select)
buttonplus.bind('<Button-1>',select)
buttonsemicolon.bind('<Button-1>',select)
buttongreaterthan.bind('<Button-1>',select)
buttonlessthan.bind('<Button-1>',select)
buttonquestionmark.bind('<Button-1>',select)




root.mainloop()